### ISSUE TITLE
Relative file references using require

### ISSUE THREAD

**Issue by rtm** [sverweij/js-makedepend#9]
Consider a tree such as

    home
      functions
        src
          index.ts

Where `index.ts` has a line such as

    require('../serviceAccountKey.json');

Now I run `js-makedepend` from `home`, using the command

    js-makedepend functions/src/index.ts

The output is:

    # cjs dependencies
    ./functions/src/index.ts: \
        ../serviceAccountKey.json

But this path is wrong. Instead of `../serviceAccountKey.json`, which `make` interprets relative to `home`, it should be `./functions/serviceAccountKey.json`. In other words, I think it has to do the path arithmetic for me. Or am I missing something?

**Comment by sverweij** [comment]
Your expectation is correct. 

I suspect there's something wrong specific to .json dependencies.

**Comment by sverweij** [comment]
I've replicated your setup in the unit test folder. 

The problem doesn't occur in that setup, however; so
running `js-makedepend -f - test/fixtures/ts/src/index.ts` on this...
```
test
├── fixtures
│   └── ts
│       ├── src
│       │   └── index.ts
│       └── things.json
```

... with this as contents of `index.ts`:

```typescript
require('../things.json');
```

... produces what you'd expect:
```makefile
# DO NOT DELETE THIS LINE -- js-makedepend depends on it.

# amd dependencies
# cjs dependencies
test/fixtures/ts/src/index.ts: \
	test/fixtures/ts/things.json

# es6 dependencies
```

**However** if I move or remove `things.json` I *do* get the same result you get. This is what happens:
- js-makedepend cannot find `things.json` at the location specified ('../'). 
- it silently tries the best it can make of the situation, which is currently to output the unresolved path

It would've been more elegant if js-makedepend had told you about it (e.g. with a warning on console) - I'll see if I can make that happen.

@rtm can you confirm your `functions` folder indeed doesn't contain `serviceAccountKey.json` (file name case might be relevant, depending on the file system you're using)?

**Comment by rtm** [comment]
yes, that was the problem, thanks for tracking it down. That file doesn't
exist at the moment the dependencies are being calculated due to the way my
make/build process works. (However, notice that an `import '../foo`);` is
handled properly whether it exists or not IIRC.)

Bob

**Comment by sverweij** [comment]
@ the `import '../foo';` => I haven't been able to reproduce that on my environment - the TypeScript compiler washes it out before js-makedepend can resolve the path. 

I'll make an item on the roadmap to have js-makedepend issue warnings when it couldn't find things

**Comment by rtm** [comment]
Many thanks for dealing with this.
